const teamMembers = [
    {
      name: 'Яна Луніна',
      role: 'Team Lead/Developer',
      avatar: 'image',
      telegram: '',
      github: '',
      linkedin: '',
    },
    {
        name: 'Ольга',
        role: 'Scrum Master/Developer',
        avatar: 'image',
        telegram: '',
        github: '',
        linkedin: '',
      },
      {
        name: 'Олексій Кочуров',
        role: 'Developer',
        avatar: 'image',
        telegram: '',
        github: '',
        linkedin: '',
      },
      {
        name: 'Іван Пантелюк',
        role: 'Developer',
        avatar: 'image',
        telegram: '',
        github: '',
        linkedin: '',
      },
      {
        name: 'Юрій Василенко',
        role: 'Developer',
        avatar: 'image',
      },
      {
        name: 'Людмила Козицька',
        role: 'Developer',
        avatar: 'image',
        telegram: '',
        github: '',
        linkedin: '',
      },
      {
        name: 'Олександр Клин',
        role: 'Developer',
        avatar: 'image',
        telegram: '',
        github: '',
        linkedin: '',
      },
      {
        name: 'Ельвіра Будна',
        role: 'Developer',
        avatar: 'image',
        telegram: '',
        github: '',
        linkedin: '',
      },
      {
        name: 'Олег',
        role: 'Developer',
        avatar: 'image',
        telegram: '',
        github: '',
        linkedin: '',
      },
      {
        name: 'Інна Покидько',
        role: 'Developer',
        avatar: 'image',
        telegram: '',
        github: '',
        linkedin: '',
      },
      {
        name: 'Віктор Адамович',
        role: 'Developer',
        avatar: 'image',
        telegram: '',
        github: '',
        linkedin: '',
      },
      {
        name: 'Сергій',
        role: 'Developer',
        avatar: 'image',
        telegram: '',
        github: '',
        linkedin: '',
      },
      {
        name: 'Ярослав',
        role: 'Developer',
        avatar: 'image',
        telegram: '',
        github: '',
        linkedin: '',
      },
  ];
  
  export default teamMembers;