const teamMembers = [
  {
    index: 1,
    // name: 'Яна Луніна',
    // role: 'Team Lead/Developer',
    // avatar: 'image',
    // telegram: '@ynln69',
    // github: 'https://github.com/Ynln69',
    // linkedin: 'https://www.linkedin.com/in/yana-lunina/',
  },
  {
    index: 2,
    name: 'Яна Луніна',
    role: 'Team Lead/Developer',
    avatar: '/creators/5.jpg',
    telegram: '@ynln69',
    github: 'https://github.com/Ynln69',
    linkedin: 'https://www.linkedin.com/in/yana-lunina/',
  },
  {
    index: 3,
    name: 'Ольга Кривулько',
    role: 'Scrum Master/Developer',
    avatar: 'image',
    telegram: '@olgakryv',
    github: 'OlgaOO7',
    linkedin: 'https://www.linkedin.com/in/olga-kryvulko/',
  },
  {
    index: 4,
    name: 'Сергій',
    role: 'BackEnd Developer',
    avatar: 'image',
    telegram: '',
    github: '',
    linkedin: '',
  },
  {
    index: 5,
    name: 'Ярослав',
    role: 'BackEnd Developer',
    avatar: 'image',
    telegram: '',
    github: '',
    linkedin: '',
  },
  {
    index: 6,
    name: 'Віктор Адамович',
    role: 'BackEnd Developer',
    avatar: 'image',
    telegram: '',
    github: '',
    linkedin: '',
  },
  {
    index: 7,
    name: 'Юрій Василенко',
    role: 'FullStack Developer',
    avatar: 'image',
  },
  {
    index: 8,
    name: 'Олексій Кочуров',
    role: 'FrontEnd Developer',
    avatar: 'image',
    telegram: '',
    github: '',
    linkedin: '',
  },
  {
    index: 9,
    name: 'Іван Пантелюк',
    role: 'FrontEnd Developer',
    avatar: 'image',
    telegram: '',
    github: '',
    linkedin: '',
  },
  {
    index: 10,
    name: 'Людмила Козицька',
    role: 'FrontEnd Developer',
    avatar: 'image',
    telegram: '',
    github: '',
    linkedin: '',
  },
  {
    index: 11,
    name: 'Олександр Клин',
    role: 'FrontEnd Developer',
    avatar: 'image',
    telegram: '',
    github: '',
    linkedin: '',
  },
  {
    index: 12,
    name: 'Ельвіра Будна',
    role: 'FrontEnd Developer',
    avatar: 'image',
    telegram: 'https://t.me/ElviraBudna',
    github: 'https://github.com/ElviraBudna',
    linkedin: 'https://www.linkedin.com/in/elvira-budna/',
  },
  {
    index: 13,
    name: 'Олег',
    role: 'FrontEnd Developer',
    avatar: 'image',
    telegram: '',
    github: '',
    linkedin: '',
  },
  {
    index: 14,
    name: 'Інна Покидько',
    role: 'FrontEnd Developer',
    avatar: 'image',
    telegram: '',
    github: '',
    linkedin: '',
  },
];

export default teamMembers;
